from random import choice
import os
import time



total = 0
score = 0

time_limit = 5
start_time = time.time()

while total != 10:
    os.system('clear')
    elapsed_time = time.time() - start_time

    list = [ "physique" , "italie" , "precieux" , "panneaux" , "boutons" , "renoncer" , "etudiante" , "souffrant" , "banniere" , "affectes" , "deal" , "differentes" , "moisissure" , "hawaii" , "masseur" , "effrayants" , "tfc" , "csss" , "coulisser" , "gwena" , "supportons" , "avanceront" , "rapa"
,"totalement", "charge" , "atmosphere" , "sam" , "expansion" , "statue" , "assiste" , "terminal" , "revu" , "voudraient" , "binaire" , "opte" , "eprouvant" , "repartit" , "implicites" , "gazoduc" , "adroitement" , "maoïste" , "monotherapie" , "phenytoin" , "battlefieldpoker" , "odontologie" , "styling"
"soutien" , "bain" , "installations" , "repartition" , "frederic" , "designer" , "communion" , "maintes" , "qualifications" , "cp" , "entendons" , "lances" , "immortelle" , "arêtes" , "uchiwa" , "gardner" , "setsuna" , "maj" , "msv" , "magnetiseur" , "wwwgetmintedcasino" , "trin" , "tiene"
"majorite" , "gars" , "greve" , "vingtaine" , "hall" , "cheque" , "semblaient" , "passionnant" , "crains" , "arrivons" , "batman" , "symboliquement" , "duplex" , "rejouissances" , "festivaliers" , "baroin" , "celeste" , "ascenceur" , "det" , "moulants" , "wwwwilliamhillcasinocom" , "demarques" , "cadbury"
"tandis" , "notes" , "traitements" , "sons" , "dirigeant" , "indiens" , "officielles" , "appliquent" , "vole" , "marquant" , "refermer" , "meuf" , "iconographie" , "risk" , "echalotes" , "soies" , "velib" , "means" , "affacturage" , "hypercholesterolemie" , "cambriole" , "malka" , "consistantes"
"livres" , "tente" , "attirer" , "vierge" , "leve" , "insectes" , "travailleur" , "legendes" , "festivals" , "documentaires" , "riposte" , "insuffisants" , "yards" , "buccale" , "wwwbet" , "alignements" , "indecente" , "ralisation" , "motivante" , "bordeau" , "renouent" , "aker" , "retendre"
"piece" , "patrimoine" , "k" , "papiers" , "remet" , "sortis" , "eternite" , "sortira" , "cavaliers" , "passager" , "sonnerie" , "exiles" , "fidel" , "reves" , "croustillant" , "desinteressement" , "sarrasins" , "individuation" , "supplementaires" , "gestuelles" , "maka" , "succombant" , "landivisiau"
"large" , "candidats" , "populaires" , "separation" , "tombee" , "scandale" , "jean-paul" , "marchait" , "secs" , "dim" , "cyber" , "pff" , "verticaux" , "ww" , "protegez" , "pâtes" , "viadeo" , "ciselee" , "canut" , "vernes" , "wwwcrazypokercom" , "meng" , "agreg"
"faite" , "apprentissage" , "quotidienne" , "sexuelle" , "adherents" , "bouteilles" , "musicien" , "emprunter" , "licenciement" , "conservateurs" , "fixait" , "inimaginable" , "constructives" , "bardeaux" , "sauveteurs" , "demi-vie" , "uniformiser" , "hyperactif" , "tellurique" , "storyline" , "wwwcaptaincooks"
"poids" , "lyon" , "faim" , "lumieres" , "denis" , "nancy" , "sanction" , "expliquant" , "renouveau" , "designer" , "puiser" , "entreposage" , "coachs" , "trac" , "sv" , "audimat" , "ehess" , "ricanement" , "shekels" , "etl" , "wwwbetuspokercom" , "quiksilver" , "rendormit"
"decide" , "seance" , "quasiment" , "constat" , "intelligent" , "exposer" , "problematiques" , "levant" , "laissee" , "compatibles" , "commentateurs" , "miseres" , "incantation" , "labos" , "tentais" , "afd" , "repandait" , "troublent" , "survivor" , "nosco" , "lumbago" , "reservee" , "salaison"
"perdu" , "langage" , "signature" , "prenait" , "cinquante" , "bertrand" , "guerir" , "louise" , "joints" , "capteurs" , "retentit" , "imprime" , "obeissent" , "cobaye" , "brisent" , "mi-juin" , "devolution" , "anesthesique" , "clamant" , "medes" , "fauchon" , "irreelles" , "tâtant"
"joue" , "vecu" , "clientele" , "harmonie" , "ferai" , "rendait" , "serenite" , "benediction" , "primordial" , "abordes" , "tropicale" , "adonner" , "landry" , "culpa" , "regrettant" , "livide" , "persistait" , "acculturation" , "caprins" , "enthousiasmes" , "talmudique" , "uzi" , "extatiques"
"fonds" , "offrent" , "variete" , "reglementation" , "pdf" , "resume" , "fermement" , "redoutable" , "planning" , "resolutions" , "supposee" , "cidre" , "johann" , "standardisation" , "iaque" , "europ" , "exerçaient" , "frelon" , "dombes" , "ankh" , "arawak" , "noterons" , "deferee"
"changement" , "attente" , "quartiers" , "entraîne" , "sensations" , "penetrer" , "ponts" , "interroge" , "nov" , "substitution" , "synchronisation" , "crees" , "sonnait" , "cruelles" , "bret" , "belligerants" , "allende" , "apprend-on" , "lenergie" , "fraie" , "ebe" , "photographiant" , "neogothique"
"achat" , "arme" , "profite" , "ecrite" , "d''oeuvre" , "ignorance" , "arrivera" , "êtes-vous" , "mentalite" , "surf" , "contree" , "biomasse" , "contre-attaque" , "replace" , "magalie" , "presidait" , "debbie" , "smoke" , "pensable" , "ederson" , "kyuubi" , "etaye" , "bâcles"
"d''accord" , "detail" , "coucou" , "arrivait" , "francais" , "causer" , "therapie" , "general" , "lucratif" , "grenier" , "kw" , "seche" , "breuvage" , "feedback" , "reveils" , "triples" , "dechaîner" , "breuil" , "chicoree" , "casinoelegance" , "evocatrices" , "bredouilla" , "contains"
"compagnie" , "nez" , "rêves" , "inclus" , "qualifie" , "verbe" , "gigantesque" , "vitamines" , "la-dessus" , "beneficiant" , "sense" , "orales" , "arborant" , "fuis" , "quelquun" , "ecoutaient" , "administrees" , "recouvre" , "revêtait" , "amalric" , "miteuse" , "talal" , "zebda"
"conseils" , "franchement" , "enceinte" , "voudrait" , "optimisation" , "pneus" , "edf" , "recyclage" , "dore" , "quelques-unes" , "conquêtes" , "apprendrez" , "bilingues" , "affichages" , "depardieu" , "bandelettes" , "associ" , "definitivement" , "kandinsky" , "sayed" , "godemiche" , "nordeste" , "decroix"
"sort" , "fleurs" , "positions" , "fantastique" , "rennes" , "sarah" , "supplement" , "sculpture" , "facultes" , "calcule" , "tailleur" , "willy" , "puissamment" , "orange" , "spaghetti" , "telescopes" , "vacille" , "hh" , "poursuivirent" , "sunpalacecasino" , "exploitez" , "muir" , "medica"
"utilise" , "savez" , "retirer" , "chaînes" , "surveiller" , "cela" , "toronto" , "departemental" , "spatiale" , "chaussettes" , "permanentes" , "instaure" , "muqueuse" , "indisponibilite" , "voterai" , "cern" , "balançait" , "bine" , "paristech" , "downey" , "proa" , "hofmann" , "tripod"
"ya" , "sent" , "sourit" , "têtes" , "nomme" , "triple" , "identifie" , "limitation" , "retraites" , "aise" , "detracteurs" , "cinemas" , "signalement" , "cle" , "couve" , "upon" , "confiseries" , "noirci" , "tyrolienne" , "jtm" , "iil" , "voues" , "sanctifiante"
"parties" , "laissant" , "favoriser" , "fonde" , "revelation" , "vertus" , "confie" , "confederation" , "enfonce" , "familiaux" , "craignait" , "agrandit" , "pride" , "boucles" , "dansante" , "commandite" , "grosjean" , "capoter" , "souplement" , "maximacasino" , "buffenbarger" , "citibank" , "kuroshi"
"vendredi" , "eaux" , "deviennent" , "pattes" , "provenance" , "caisses" , "typiquement" , "lyonnais" , "rallye" , "gagnants" , "arrivants" , "disait-il" , "cdh" , "marois" , "jouvence" , "toul" , "elevateur" , "intervenez" , "clicker" , "laïus" , "sklanasky" , "bolchoï" , "radiothrapie"
"regime" , "victime" , "ceremonie" , "signal" , "mines" , "barriere" , "messagerie" , "nana" , "enfoncer" , "planifier" , "fraudes" , "disparites" , "antidote" , "deezer" , "cire" , "intervenante" , "rejoignirent" , "higgins" , "cioran" , "bonnasse" , "nne" , "laeti" , "lagrable"
"and" , "donnent" , "e" , "massage" , "câble" , "bêtes" , "interessent" , "lignee" , "plateaux" , "deranger" , "paradigme" , "symetrie" , "beaulieu" , "coûterait" , "navets" , "fluor" , "mures" , "hawkins" , "patrouiller" , "inhale" , "wwwdublinbetcom" , "jet-ski" , "kisa"
"prochain" , "inscrit" , "gratuite" , "tresor" , "conducteur" , "detention" , "from" , "fmi" , "jolis" , "insister" , "verrai" , "mediane" , "roumaine" , "reverend" , "effacees" , "lavant" , "confiez" , "enlaces" , "eiji" , "wallstreetcasino" , "cantonnees" , "indifferenciee" , "boumediene"
"lieux" , "performance" , "realisee" , "portait" , "enquêtes" , "lisant" , "autriche" , "reduction" , "laissons" , "confreres" , "enculer" , "peche" , "prêche" , "amphi" , "rappelee" , "astronaute" , "nouchette" , "skip" , "trudel" , "dissolvent" , "actionpoker" , "elite" , "tanit"
"cheveux" , "consequence" , "emplacement" , "armees" , "dote" , "tit" , "condamnation" , "nourrit" , "barrieres" , "suggere" , "julian" , "foutue" , "cruise" , "redigees" , "mossad" , "detecteur" , "late" , "aplanir" , "frapperent" , "lautrec" , "absurdit" , "simmel" , "tracey"
"capacite" , "europeens" , "fournit" , "mentionner" , "refugies" , "fondamental" , "philosophique" , "regiment" , "allaitement" , "monture" , "coûtera" , "ademe" , "lavez" , "pompee" , "modifs" , "francilien" , "rythment" , "fievre" , "trouees" , "nkm" , "jugeois" , "tennant" , "rabattement"
"dos" , "precis" , "honte" , "agricoles" , "ong" , "infrastructure" , "ose" , "fondements" , "lames" , "contrôle" , "blair" , "argumenter" , "refroidi" , "durante" , "incarnant" , "sammy" , "cuillerees" , "baldaquin" , "utilisez-vous" , "blanchies" , "celina" , "equi" , "gaviscon"
"regles" , "pouvant" , "evaluer" , "depasser" , "copain" , "armure" , "coiffure" , "musicales" , "bague" , "flandre" , "abonnements" , "paternelle" , "meconnue" , "paper" , "rectangulaires" , "hai" , "fractionne" , "ries" , "subterfuges" , "specialisant" , "aldebaran" , "raclure" , "mexico"
"responsable" , "dure" , "emissions" , "actuels" , "mechant" , "plaire" , "elabore" , "sembler" , "cnrs" , "http" , "baha" , "comores" , "evident" , "agde" , "saint-andre" , "reintroduire" , "debarrasses" , "mlyon" , "reconforte" , "eti" , "sikh" , "polychromie" , "isobel"
"bonnes" , "supplementaires" , "terminer" , "plait" , "ml" , "elan" , "poemes" , "qd" , "integrale" , "apprenant" , "gary" , "deviation" , "vergers" , "gousses" , "beant" , "roh" , "pastiche" , "confie-t-il" , "nw" , "barmaid" , "lanester" , "antiliberal" , "pierce"
"avance" , "elus" , "debats" , "devrais" , "participant" , "tape" , "cliquant" , "voulut" , "mortel" , "agi" , "completee" , "sautant" , "cold" , "foireux" , "onfray" , "cub" , "freinet" , "delai" , "manires" , "rivesaltes" , "larbre" , "taboo" , "côtoyons"
"joueur" , "etrange" , "relatives" , "legende" , "partage" , "quelquefois" , "edward" , "website" , "varient" , "retrouvera" , "dechirer" , "program" , "scandaleuse" , "acharnes" , "diurne" , "diffrent" , "keynote" , "bienfaisant" , "meuvent" , "heroïquement" , "demasques" , "pigmentaires" , "lance-pierre"
"dossier" , "etablir" , "suppose" , "fausse" , "serre" , "mondialisation" , "charbon" , "mecaniques" , "resident" , "draps" , "ardent" , "wwe" , "insaisissable" , "syst" , "crottes" , "nepalais" , "reels" , "minneapolis" , "mouvemens" , "wildjackcasino" , "azhar" , "poiret" , "normaliens"
"armee" , "format" , "bizarre" , "exprime" , "notions" , "profondes" , "as-tu" , "obtenue" , "continuant" , "abords" , "depart" , "charia" , "insatiable" , "succursales" , "sacrifiee" , "neologisme" , "braque" , "sonates" , "henkel" , "fournirons" , "semblerai" , "campait" , "drafte"
"annonce" , "immobilier" , "dejeuner" , "limitee" , "immediate" , "souffrances" , "variees" , "rap" , "delivrer" , "autonomes" , "constructif" , "gamma" , "reste-t-il" , "admiratif" , "kurdistan" , "desdites" , "precisa" , "galit" , "villarreal" , "redd" , "dedicacee" , "joffrey" , "kale"
"com" , "enfance" , "voisins" , "christophe" , "vagues" , "colloque" , "sovietique" , "alias" , "pique" , "percer" , "sicile" , "huîtres" , "portais" , "perquisition" , "abstentions" , "sodome" , "cormier" , "scanne" , "sempiternelle" , "recommendations" , "polype" , "auto-critique" , "debacle"
"suivant" , "classes" , "japonais" , "crimes" , "rajouter" , "exploration" , "deesse" , "âgee" , "appelant" , "etait-ce" , "voirie" , "concurrencer" , "chargea" , "hernie" , "ebloui" , "resserre" , "chacal" , "bissau" , "statistics" , "tournay" , "koalas" , "perquisitionne" , "piazzolla"
"six" , "serveur" , "moral" , "diplôme" , "amusant" , "equipe" , "entrepris" , "sonores" , "poussant" , "reposant" , "recherches" , "gâchis" , "provoqua" , "dingues" , "trahissent" , "plissa" , "chaînon" , "double-cliquez" , "tuerai" , "saint-eustache" , "bettinghills" , "scanning" , "loreille"
"membre" , "nations" , "annonces" , "laissent" , "proportion" , "superieures" , "fluide" , "visent" , "lycees" , "kaori" , "onereux" , "decidons" , "mouilles" , "tx" , "ratzinger" , "voteront" , "inflammables" , "bipolaires" , "ferreira" , "lobbyiste" , "thromboses" , "desireraient" , "pidgin"
"essayer" , "atelier" , "hommage" , "expose" , "interesser" , "etroite" , "attaque" , "susciter" , "cases" , "paires" , "canards" , "cho" , "csc" , "confident" , "auditifs" , "monteur" , "fievres" , "giono" , "ibrahimovic" , "federatrice" , "victorine" , "hayward" , "gelatineux"
"double" , "superbe" , "riviere" , "onu" , "urbaine" , "usines" , "consultant" , "expo" , "coutumes" , "recommander" , "fofo" , "attestent" , "chaussees" , "canevas" , "fp" , "massant" , "oe" , "capifrance" , "soulignez" , "antisocial" , "royalvegasonlinecasinocom" , "sommeils" , "funambules"
"tels" , "cree" , "appartient" , "voler" , "entrees" , "organe" , "fievre" , "valide" , "eva" , "propagation" , "annonça" , "evolutive" , "papas" , "feodal" , "permeabilite" , "hebergee" , "fataliste" , "serti" , "recharge" , "chiisme" , "wingowspoker" , "republication" , "jovan"
"contrat" , "remarque" , "fan" , "plaque" , "ignore" , "depenser" , "jan" , "cauchemar" , "representee" , "chaussee" , "declarait" , "detenue" , "bouleversee" , "genitales" , "lunatique" , "zapping" , "jfk" , "nauseabond" , "impreza" , "xlr" , "degager" , "djelfa" , "baleiniers"
"paix" , "centres" , "connus" , "diminution" , "significative" , "blues" , "demeurent" , "devoile" , "urbaines" , "repandue" , "vire" , "rocheux" , "representera" , "accelerations" , "partialite" , "decu" , "diffuses" , "parachutisme" , "pister" , "preferent" , "btiments" , "cotre" , "heurtera"
"proche" , "recours" , "viande" , "puissante" , "regrette" , "medaille" , "anus" , "vaches" , "hey" , "rebellion" , "plants" , "dernieres" , "docs" , "shinji" , "imprevues" , "h1n1" , "affolement" , "loque" , "rencontrerait" , "primecasino" , "newnum" , "indeterminees" , "drômois"
"economie" , "urgence" , "parlant" , "chevalier" , "destinees" , "olympique" , "continuation" , "complications" , "asiatiques" , "fleches" , "price" , "pearl" , "tolerant" , "prononcent" , "drastiques" , "harbor" , "decretee" , "temari" , "transportera" , "casinokingdom" , "echographique" , "contentai" , "stij"
"verite" , "etats-unis" , "pensent" , "rempli" , "progresser" , "loisir" , "occidental" , "dangereuses" , "estimer" , "masques" , "yamaha" , "parieurs" , "camescope" , "interferer" , "lamartine" , "annouchka" , "generalisees" , "suresnes" , "cajoler" , "grayson" , "endurcit" , "rani" , "offusques"
"probablement" , "utilisateur" , "trente" , "apporte" , "gre" , "vice" , "blocage" , "hesiter" , "interrogation" , "obtiennent" , "blogueurs" , "cuvee" , "comparaître" , "resurgence" , "dupliquer" , "laissez-passer" , "santini" , "semblait-il" , "billions" , "elvire" , "babord" , "baden-baden" , "reponds-moi"
"raisons" , "danse" , "institution" , "signer" , "rappelons" , "ajoutee" , "salons" , "bibliotheques" , "notice" , "colons" , "tintin" , "adresses" , "recipients" , "transcender" , "obscene" , "resorption" , "talbot" , "turbulents" , "traiterons" , "châtelaine" , "castoriadis" , "aries" , "imao"
"apprendre" , "locales" , "culturelle" , "magnifiques" , "filtre" , "artistiques" , "renforce" , "pv" , "planetes" , "seduction" , "glissement" , "pathologique" , "obsoletes" , "reequilibrage" , "perchoir" , "dynamic" , "cierge" , "omerta" , "piaule" , "explicitee" , "compte-tours" , "potvin" , "dorne"
"lit" , "xd" , "revele" , "possedent" , "connues" , "systematique" , "recommencer" , "rio" , "traitees" , "ouvertures" , "precipiter" , "baker" , "imagines" , "tendon" , "sous-officiers" , "bullet" , "creator" , "guerilleros" , "rougeâtres" , "shy" , "bojan" , "syllogismes" , "dessay"
"payer" , "kg" , "automne" , "plats" , "incontournable" , "logistique" , "cause" , "boucles" , "jument" , "corporelle" , "lang" , "couchage" , "accumulees" , "soviets" , "compresse" , "introduisit" , "remercies" , "exuberante" , "grabuge" , "moriarty" , "profondment" , "boisset" , "libro"
"conscience" , "progres" , "couper" , "ressort" , "gouvernance" , "herbes" , "françoise" , "breton" , "ie" , "relaxation" , "petroliere" , "scelle" , "recoltes" , "comportementales" , "pelerinages" , "frontenac" , "inondees" , "manifestees" , "ashram" , "casinodelrio" , "handicapes" , "arriere-boutique" , "irp"
"afrique" , "vas" , "age" , "mn" , "superieurs" , "dangereuse" , "preferee" , "helene" , "regroupant" , "ignorant" , "gouverne" , "tonneau" , "allegresse" , "referencer" , "decompression" , "kk" , "clarence" , "avt" , "degage" , "sbgglobalcasino" , "tenormin" , "hedwige" , "hotaru"
"certaine" , "mobile" , "belgium" , "rigueur" , "genres" , "aube" , "amuse" , "emma" , "soulever" , "reportages" , "attaquants" , "sacerdoce" , "jurer" , "astreinte" , "affole" , "mats" , "rattrapee" , "synthes" , "sedatif" , "boycottage" , "valognes" , "dirigerait" , "antonov"
"universite" , "constitution" , "feuille" , "inquiete" , "tristesse" , "sauve" , "xvi" , "profs" , "preparent" , "bassins" , "acceptez" , "meriterait" , "licencier" , "leila" , "pong" , "bombe" , "ahhhh" , "titia" , "palu" , "clubplayercasino" , "wilderness" , "fraterniser" , "rivalisaient"
"pieds" , "scientifiques" , "instruments" , "condamne" , "partisans" , "ny" , "formats" , "maternite" , "chanteurs" , "reduisant" , "respectees" , "corbeille" , "agora" , "commentant" , "inaugurale" , "faisoit" , "prevoyaient" , "alcoolise" , "amalia" , "introductive" , "regroupaient" , "vardenafil" , "electeu"
"explique" , "envoye" , "gloire" , "affirme" , "conformite" , "deteste" , "jouez" , "dc" , "reglementaire" , "vaccins" , "navale" , "inconfort" , "lorrain" , "sous-sols" , "predicateurs" , "rejoindront" , "pendentifs" , "golfs" , "raccordee" , "tablature" , "starsky" , "lcen" , "terri"
"police" , "pauvres" , "jusque" , "grece" , "etant" , "saisi" , "privilege" , "descriptif" , "adherer" , "audi" , "sante" , "admins" , "lynch" , "collations" , "dietetiques" , "mandature" , "meuh" , "multilateraux" , "galbe" , "insubordination" , "engraisse" , "jex" , "rollet"
"courant" , "lance" , "francs" , "jai" , "futures" , "proie" , "soixante" , "sentant" , "die" , "elisabeth" , "planchers" , "graal" , "paraîtra" , "engranger" , "opportune" , "entrejambe" , "copinage" , "abrupt" , "aed" , "radek" , "harmon" , "resisterent" , "dpsn"
"garder" , "hôpital" , "serai" , "representer" , "fragile" , "reparer" , "affiches" , "etudie" , "magnetique" , "renverser" , "devions" , "infarctus" , "exiges" , "motions" , "modelisme" , "flasque" , "virulentes" , "mandala" , "göteborg" , "prcdents" , "lod" , "seroconversion" , "guediguian"
"memoire" , "amelioration" , "etudier" , "module" , "demoiselle" , "croyances" , "ruines" , "arsenal" , "fragiles" , "spontanement" , "pilules" , "organisons" , "emoi" , "intriguee" , "arriveras" , "passe-passe" , "aspinalls" , "birmane" , "x2" , "pacioretty" , "hadja" , "muselier" , "epargnait"
"relations" , "restaurant" , "extension" , "end" , "accorder" , "aie" , "impressionnante" , "peindre" , "inspiree" , "legitimes" , "secouer" , "comptais" , "canin" , "cylindrique" , "ivres" , "inhiber" , "fais-moi" , "suscitait" , "quantifiable" , "prevenance" , "wwwskykingscasinocom" , "distal" , "rheteurs"
"assurance" , "retard" , "baiser" , "pardon" , "stephane" , "box" , "rassemble" , "derniere" , "em" , "pus" , "bourreau" , "concentra" , "dora" , "delirante" , "monnet" , "encablures" , "sigles" , "malagasy" , "integrations" , "tison" , "nak" , "mariama" , "sequestrations"
"caractere" , "savent" , "attaquer" , "evoque" , "couteau" , "solidaire" , "nôtre" , "debuter" , "competent" , "bad" , "quatuor" , "impassible" , "claquement" , "inclinant" , "bistro" , "gratifie" , "circulatoire" , "malone" , "blâme" , "roussi" , "merz" , "nihilistes" , "medusee"
"perdre" , "etrangers" , "faciliter" , "bleus" , "pharmacie" , "silhouette" , "deuil" , "telecommunications" , "juan" , "contours" , "supporte" , "mia" , "mutualite" , "integrisme" , "maladive" , "dmp" , "devolues" , "gracieuses" , "demolis" , "hips" , "motoriste" , "savoirs-faire" , "phalaenopsis"
"premieres" , "espagne" , "repose" , "regards" , "pa" , "chantiers" , "votes" , "aidant" , "visions" , "interlocuteurs" , "intrigues" , "trois-rivieres" , "veaux" , "emeut" , "fabrications" , "nattes" , "etalait" , "outrepasser" , "martelant" , "gutshotcom" , "exploiteur" , "krupp"
"maître" , "gratuits" , "forts" , "abus" , "couronne" , "jouets" , "rumeur" , "senateur" , "incroyablement" , "elysee" , "thriller" , "demolir" , "incorrecte" , "detectee" , "dechaîne" , "microorganismes" , "desoler" , "buttes" , "trec" , "coolcatcasino" , "q.i." , "anori" , "enroulait"
"approche" , "ere" , "disparu" , "defis" , "prêtres" , "critere" , "nommee" , "raconte" , "interieurs" , "occidentales" , "farouche" , "remportant" , "maçons" , "aleatoirement" , "quilles" , "relegues" , "hautes-pyrenees" , "cartesienne" , "donnedieu" , "interrogeaient" , "nuds" , "aimee" , "sango"
"cour" , "superieure" , "collective" , "mobilisation" , "verser" , "fonctionnent" , "entrent" , "impossibilite" , "reconnais" , "devises" , "piete" , "posais" , "grace" , "grid" , "dechus" , "jalousies" , "febrilement" , "curateur" , "abrites" , "coussinet" , "sahelienne" , "prts" , "abymes"
"professionnels" , "neige" , "mariee" , "cri" , "solitude" , "colonnes" , "suivis" , "aires" , "combinaisons" , "elargissement" , "defier" , "juvenile" , "enormement" , "mazout" , "digestives" , "refasse" , "fragilises" , "valium" , "miaou" , "grattes" , "betuspoker" , "acculer" , "actualisant"
"bord" , "bisous" , "poissons" , "installe" , "ressentir" , "christianisme" , "retablir" , "entrant" , "jumeaux" , "pathologie" , "christopher" , "peage" , "gta" , "explorant" , "resolut" , "handisport" , "exellent" , "entreprends" , "inhibitions" , "mta" , "petrograd" , "zieuter" , "expliquiez"
"preuve" , "cle" , "dizaines" , "compagnon" , "façade" , "estomac" , "sexuelles" , "resistant" , "employee" , "recommence" , "fragment" , "tac" , "soc" , "facies" , "crous" , "aggravent" , "rhodia" , "journellement" , "telluriques" , "bisevac" , "consolante" , "merad" , "teridax"
"evolution" , "options" , "hebergement" , "blesse" , "corse" , "sphere" , "credibilite" , "kim" , "locataires" , "mauritanie" , "mathilde" , "laisserai" , "tiers-monde" , "vingt-sept" , "ei" , "sous-produits" , "aussie" , "cymbales" , "cardin" , "memo" , "ranieri" , "gausser" , "grudge"
"respect" , "decide" , "cadres" , "instants" , "rendez" , "appliquee" , "gaulle" , "opposants" , "apôtres" , "essaient" , "enfuit" , "informaticien" , "coli" , "hivernage" , "evaluant" , "cdp" , "niko" , "georgiens" , "milf" , "bcq" , "kati" , "mateur" , "senatus-consulte"
"eglise" , "eventuellement" , "guilde" , "portail" , "nest" , "developpes" , "infirmiere" , "obligatoires" , "rideau" , "illegal" , "surgir" , "surgissent" , "ward" , "fût-ce" , "assoiffes" , "silos" , "plantent" , "tribulus" , "lecons" , "habillez" , "attenants" , "devissez" , "crapuleuse"
"forces" , "dynamique" , "souffrance" , "drogue" , "indicateurs" , "espoirs" , "ont-ils" , "extra" , "degustation" , "danseurs" , "ivresse" , "auditions" , "effrenee" , "enduro" , "carafe" , "lez" , "economisez" , "magnifier" , "transsexuels" , "huygens" , "finlandaises" , "monolithes" , "paieras"
"union" , "reconnaissance" , "modification" , "planification" , "cahier" , "putain" , "oublions" , "licences" , "cloud" , "interpretations" , "gabarit" , "inerte" , "colossal" , "len" , "succombe" , "postant" , "traverserent" , "robinetterie" , "certifiant" , "imager" , "lug" , "epiait" , "iriez"
"importance" , "equilibre" , "quête" , "aide" , "verrez" , "varietes" , "quarantaine" , "recourir" , "calories" , "debris" , "tempo" , "en-tête" , "eolas" , "parraine" , "perrier" , "treuil" , "diuretique" , "cacahuete" , "roulottes" , "everett" , "c.d." , "malaisienne" , "metisses"
"faible" , "design" , "graves" , "protocole" , "education" , "rendit" , "aident" , "detaille" , "agitation" , "cs" , "apprendra" , "sore" , "talus" , "litterale" , "reapparaît" , "friedman" , "croche" , "surcouf" , "immediate" , "mûrier" , "arguties" , "guano" , "amibes"
"retrouve" , "concurrence" , "legere" , "remercier" , "municipalite" , "syrie" , "quoiqu" , "spoiler" , "pertinent" , "menes" , "excitee" , "motorola" , "structures" , "confusions" , "debuteront" , "equerre" , "chassee" , "causses" , "larsson" , "firstwebcasino" , "bolcheviks" , "dussault" , "accesoires"
"maladie" , "facteurs" , "adapte" , "depit" , "collectivite" , "set" , "moule" , "vegetation" , "respectent" , "silencieuse" , "zac" , "domenech" , "extremiste" , "prsident" , "pouvoit" , "dissemblables" , "faa" , "panels" , "radium" , "incorporels" , "floppee" , "floribert" , "propitiation"
"dois" , "plage" , "humeur" , "presidence" , "moncler" , "visiteur" , "inciter" , "mercure" , "hospitalisation" , "intenses" , "restants" , "onglets" , "archetype" , "tonalites" , "debordent" , "excedentaires" , "europeen" , "concretisent" , "igas" , "narguile" , "mugler" , "malfaisantes" , "ñ"
"prêt" , "defendre" , "calendrier" , "pleurer" , "officier" , "eventuelle" , "exportation" , "niger" , "reprocher" , "deroulent" , "cci" , "applaudir" , "lle" , "aisees" , "apprecie" , "dubrovnik" , "cops" , "essayerent" , "elucidation" , "agoniste" , "salorio" , "non-violent" , "fuirent"
"course" , "repond" , "transmission" , "culturelles" , "semblables" , "produite" , "respectant" , "modernisation" , "incite" , "compliquee" , "tahiti" , "selection" , "emerite" , "distribuant" , "those" , "abonnee" , "boubacar" , "comes" , "desolee" , "subsequent" , "argue" , "estado" , "ribavirin"            
"total" , "finit" , "preciser" , "individuelle" , "representations" , "localisation" , "croisiere" , "fantaisie" , "traitee" , "sorciers" , "etoit" , "meurtriers" , "militent" , "brie" , "pontoise" , "soutint" , "silverstone" , "payne" , "al-islam" , "bells" , "wwwvcpokercom" , "bigouden" , "pussycat"
"administration" , "trouvait" , "intermediaire" , "plateforme" , "regionaux" , "activement" , "epais" , "violation" , "tenta" , "mefiance" , "agonie" , "footballeur" , "existentielle" , "biensûr" , "repertorier" , "cad" , "aliene" , "percepteur" , "selectionnent" , "designed" , "columbo" , "mtaux" , "majestes"
"dix" , "championnat" , "reprend" , "monstre" , "designe" , "employeurs" , "so" , "meuble" , "portees" , "habituels" , "suzanne" , "hebergements" , "contentement" , "derivation" , "nuitee" , "bonhommes" , "abattues" , "sonde" , "leviter" , "sarbacane" , "regardiez" , "aioros" , "concoure"
"dû" , "echanges" , "chômage" , "antoine" , "participent" , "tribunaux" , "effective" , "demandeurs" , "brown" , "villageois" , "coudes" , "fx" , "gnrique" , "orks" , "bahut" , "bid" , "zuckerberg" , "exportee" , "decisionnaires" , "transparences" , "annieduke" , "solidarit" , "aaricia"
"accord" , "employes" , "sucre" , "accueille" , "conviction" , "aborder" , "echantillon" , "applicables" , "recensement" , "deployer" , "prescrire" , "electro" , "vaudois" , "venture" , "causait" , "ascq" , "soufflerie" , "tiedeur" , "longjumeau" , "karakura" , "dvd-r" , "timeo" , "intros"
"types" , "prêts" , "cultures" , "douleurs" , "canton" , "dirigea" , "plastiques" , "bu" , "socle" , "liberalisme" , "hadopi" , "templiers" , "fl" , "ardents" , "crepis" , "exclamations" , "emdr" , "intrepides" , "celui-la" , "bcc" , "pokerlococom" , "plone" , "demi-mesures"
"parole" , "arrête" , "accepte" , "interesse" , "costume" , "lampe" , "tasse" , "nostalgie" , "trajectoire" , "lou" , "symboliques" , "council" , "mal-être" , "assigne" , "jovial" , "repugnance" , "kom" , "vois-je" , "terrifies" , "surexposition" , "sierrastarcasino" , "prenez-en" , "clerck"
"europeenne" , "experiences" , "connait" , "falloir" , "modeste" , "materiau" , "partenariats" , "a." , "batailles" , "viandes" , "vedettes" , "jme" , "meaux" , "amalgames" , "distillerie" , "verni" , "precipitant" , "decimal" , "seraing" , "edd" , "sivaguru" , "prevarication" , "franco-italien"
"soins" , "remise" , "directe" , "hautes" , "manipulation" , "evolue" , "inconscient" , "fusil" , "minimale" , "ecrivait" , "bloques" , "genereuses" , "charrette" , "kenneth" , "amon" , "ixe" , "pretentieuse" , "baisant" , "rueil" , "refuseraient" , "wwwprimecasino" , "amniocentese" , "quantifie"
"tenir" , "tradition" , "modes" , "ordinateurs" , "existant" , "approbation" , "chauffeur" , "positives" , "resolument" , "contrôlee" , "pj" , "destins" , "retrouvais" , "arrondir" , "bey" , "ballast" , "somniferes" , "dessinez" , "adoooore" , "arthuriancasino" , "wingowspokercom" , "briey" , "beotie"
"permettant" , "contient" , "chocolat" , "ampleur" , "egale" , "rentre" , "reperes" , "liberaux" , "flexibilite" , "journalisme" , "lessive" , "vieillards" , "valorise" , "speculative" , "pluraliste" , "oto" , "fagots" , "ombrelle" , "pops" , "inculper" , "pokerheavencom" , "pierre-antoine" , "aprend" ]

    print("score = ",score)
    word_choose = choice(list)
    print('ecrire '+ str(word_choose))
    game = input()

    if game == word_choose:
        os.system('clear')
        print("bien joué")
        score += 1
        total += 1
        os.system('clear')
    else:
        os.system('clear')
        print("dommage")
        score -= 1
        total += 1
        os.system('clear')

print("vous avez ", score, " points")
